### ISSUE TITLE
SCSS can not convert numeric scope fragments

### ISSUE THREAD

**Issue by thecodechef** [FichteFoll/CSScheme#11]
The Heading Scopes for Markdown Extended are not working i keep getting errors in each of the languages so HELP PLEASE!!

P.S Awesome Plugin keep doing what you do.

**Comment by FichteFoll** [comment]
What are the errors and how can I reproduce it?

**Comment by thecodechef** [comment]
Whenever i try to change the colors of either the header content or the header punctuation it gives errors
```
Errors converting from SCSScheme to CSS, return code: 65

Error: Invalid CSS after "...markup.heading.": expected class name, was "1.markdown punc..."
        in scheme/langs/_markdown.scss on line 2
        from line 215 of ~/.config/sublime-text-3/Packages/Theme - LevelUpTuts/LevelUpTuts.scsscheme
  Use --trace for backtrace.
```
to recreate this error
```scss
text.html.markdown meta.block-level.markdown markup.heading.1.markdown punctuation.definition.heading.markdown {
  @name "Markdown: Heading (Punctuation)";
  foreground: $cyan;
}
```
